- name: Build yuntailscale.exe
  run: |
    cd cmd/tailscale
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build \
      -ldflags="-s -w -H=windowsgui -extldflags '-static'" \
      -trimpath \
      -o ../../yuntailscale_tmp.exe .
    cd ../..
    upx --best --lzma yuntailscale_tmp.exe -o yuntailscale.exe
    rm yuntailscale_tmp.exe

- name: Build yuntailscaled.exe
  run: |
    cd cmd/tailscaled
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build \
      -ldflags="-s -w -extldflags '-static'" \
      -trimpath \
      -o ../../yuntailscaled_tmp.exe .
    cd ../..
    upx --best --lzma yuntailscaled_tmp.exe -o yuntailscaled.exe
    rm yuntailscaled_tmp.exe
